### ISSUE TITLE
Двигатель оси Y не работает!

### ISSUE THREAD

**Issue by qulet** [akv47/DrawBot-ramps#2]
Я делал компиляции на ардуино 1.8.9 и 1.18.18. Мотор оси "Y" не работает ни в одной компиляции
После загрузки исходного файла проекта:
Drawbot-V6_English.hex
два двигателя работают
![ramps](https://user-images.githubusercontent.com/30979927/164282463-c9c043c3-a998-47f7-bac5-3d8966de3757.jpg)
.

**Comment by akv47** [comment]
Привет [qulet](https://github.com/qulet), проверь параметр $3=3 направление моторов , $5=1 концевики на размыкание, проверь исправность концевиков и правильность их подключения https://github.com/akv47/DrawBot-ramps/blob/main/pic/connect.jpg. Видимо концевик по Y не правильно подключил.
